on: 
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules

      - name: Install packages
        run: yarn install

      - name: Lint files
        run: yarn lint

      - name: Unit tests
        run: yarn test:unit

      - name: E2E tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          start: yarn start
          wait-on: http://localhost:8080
          config: baseUrl=http://localhost:8080
